[theme]
primaryColor = "#17A2B8"
backgroundColor = "#E9F7EF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

